---
  - name: test
    hosts: all
    become: yes

    tasks:
      - name: Creating new nginx reverse proxy
        copy:
          dest: /home/test/reverse-proxy.conf
          content: |	
                 server {
                 listen 80 default_server;
                 location / {
                 proxy_pass http://127.0.0.1:9090;
                 }
                 }

      - name: Download python-server.py script
        get_url:
          url: https://github.com/inTracKas/inTracKas/blob/main/python-server.py
          dest: /home/python-server.py
          mode: '0440'

      - name: Creating new systemd service file
        copy:
          dest: /home/python-server.service
          content: |	
                 [Unit]
                 Description=Python web server with AWS IPS
                 After=multi-user.target
                 [Service]
                 Type=simple
                 Restart=always
                 ExecStart=/usr/bin/python3 /home/python-server.py
                 [Install]
                 WantedBy=multi-user.target
                 
      - name: Just force systemd to reread configs (2.4 and above)
        systemd: daemon_reload=yes
      
      - name: Enable service
        systemd:
          name: python-server
          enabled: yes
          masked: no     
          
      - name: restart service cron on centos, in all cases, also issue daemon-reload to pick up config changes
        systemd:
          state: restarted
          daemon_reload: yes
          name: python-server
          
          
          
      - name: Make sure a service is running
        systemd: state=started name=python-server